#define UNICODE_SELECTED_MODES UC_LNX, UC_MAC, UC_WIN
#define USE_I2C
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y

#define CUSTOM_SHIFT_PAIR 0x8000
#define CS(i, j) (CUSTOM_SHIFT_PAIR | ((i)&0x7F) | (((j)&0x7F) << 7))

#define TRACKBALL_OFF_TIMEOUT 650 // ms
