POINTING_DEVICE_ENABLE   = yes
POINTING_DEVICE_DRIVER   = pimoroni_trackball
PIMORONI_TRACKBALL_SCALE = 1
SRC                      += rgb.c combo.c keyoverride.c tap_dance.c
CONSOLE_ENABLE           = yes
MOUSEKEY_ENABLE          = yes
KEY_OVERRIDE_ENABLE      = yes
COMBO_ENABLE             = yes
TAP_DANCE_ENABLE         = yes